import iceTap1 from '../assets/sounds/ice-tap-1.mp3';
import iceTap2 from '../assets/sounds/ice-tap-2.mp3';
import iceTap3 from '../assets/sounds/ice-tap-3.mp3';
import iceTap4 from '../assets/sounds/ice-tap-4.mp3';
import iceTap5 from '../assets/sounds/ice-tap-5.mp3';

/**
 * Original "ice tap" sounds (~1 s, generated by scripts/generate_ice_tap.py), shaped like the
 * crystalline burst: contact tink → sparkle cascade → bell highlight → frosty fade. Several
 * variations so repeated taps don't sound mechanical, like every burst looks different.
 */
const SOUNDS = [iceTap1, iceTap2, iceTap3, iceTap4, iceTap5];

/** Default volume for the tap sound (0–1). Change at runtime with `setChimeVolume`. */
export const DEFAULT_CHIME_VOLUME = 0.35;
/** Where the mute choice is remembered (survives reloads and restarts). */
const MUTE_KEY = 'explorer.soundMuted';

let pool: HTMLAudioElement[] | null = null;
let current: HTMLAudioElement | null = null;
let lastIndex = -1;
let volume = DEFAULT_CHIME_VOLUME;
let muted = readMuted();
const listeners = new Set<() => void>();

function readMuted(): boolean {
  try {
    return typeof localStorage !== 'undefined' && localStorage.getItem(MUTE_KEY) === '1';
  } catch {
    return false;
  }
}

function sounds(): HTMLAudioElement[] | null {
  if (typeof Audio === 'undefined') return null;
  if (!pool) {
    pool = SOUNDS.map((src) => {
      const a = new Audio(src);
      a.preload = 'auto';
      a.volume = volume;
      return a;
    });
  }
  return pool;
}

function stopCurrent() {
  if (!current || current.paused) return;
  current.pause();
  current.currentTime = 0;
}

/**
 * Plays a tap sound from the beginning: a random variation (never the same one twice in a row).
 * Only one plays at a time (a new tap stops the previous one), so sounds never stack. Does
 * nothing while muted. Browsers block sound until the page has had a user gesture; that refusal
 * is silently ignored.
 */
export function playChime() {
  if (muted) return;
  const list = sounds();
  if (!list) return;
  stopCurrent();
  let i = Math.floor(Math.random() * list.length);
  if (list.length > 1 && i === lastIndex) i = (i + 1 + Math.floor(Math.random() * (list.length - 1))) % list.length;
  lastIndex = i;
  current = list[i];
  current.currentTime = 0;
  current.play().catch(() => {
    /* autoplay blocked before the first user gesture */
  });
}

/** Sets the tap-sound volume (0–1). */
export function setChimeVolume(v: number) {
  volume = Math.min(1, Math.max(0, v));
  sounds()?.forEach((a) => (a.volume = volume));
}

/** Loads the sounds ahead of the first tap so they start without delay. */
export function preloadChime() {
  sounds()?.forEach((a) => a.load());
}

export const isChimeMuted = () => muted;

/** Mutes / unmutes every tap sound; the choice is remembered. Muting stops a sound that is playing. */
export function setChimeMuted(value: boolean) {
  if (muted === value) return;
  muted = value;
  if (muted) stopCurrent();
  try {
    localStorage.setItem(MUTE_KEY, muted ? '1' : '0');
  } catch {
    /* storage unavailable: the choice lasts for this session only */
  }
  listeners.forEach((fn) => fn());
}

/** For useSyncExternalStore. */
export function subscribeChimeMuted(fn: () => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}
